name: Generate Explainers
on:
  push:
    branches: [main]
    paths: ['docs/explainers/**','.github/workflows/generate-explainers.yml']
jobs:
  generate:
    uses: Bad-Robots/Workforce/.github/workflows/generate-explainers-reusable.yml@d38c52d304e8ac70d77c9d2f979b693c0e1bbdf6
    with:
      caller_repo: ${{ github.repository }}
      base_branch: main
      workforce_ref: d38c52d304e8ac70d77c9d2f979b693c0e1bbdf6
      runner_labels: '["self-hosted","linux","ARM64","badrobots-build"]'
